### ISSUE TITLE
Fin práctica nextjs

### ISSUE THREAD

**Issue by MartaMolina01** [ULL-ESIT-DMSI-2223/nextjs-marta-molina-fernandez-alu0101603360#1]
Buenas tardes @crguezl ;

Acabo de terminar la práctica de nextjs, creo que no falta nada en el informe. Cuando pueda dígame si está correcta.

Muchas gracias. Un saludo :relaxed:

**Comment by crguezl** [comment]
@MartaMolina01 

Buen trabajo.

La [especificación](https://ull-esit-dmsi.github.io/practicas/nextjs#exercise-get-images-from-openai) de la tarea es que 👍 

Add routes to the app:

- On the first route  `/pet`  leave the current service
- On the second route `/image`add functionality to get an image from OpenAI and display it in the page.
- Update the landing page and navigation links
- Add a 404 page
- Consider the opportunity to solve it using a dynamic route

Pero tu landing page lleva sólo a la de la imagen. La idea era mantener las dos funcionalidades.

De resto lo veo bien

**Comment by MartaMolina01** [comment]
@crguezl 

Tiene razón, es como si mi cabeza hubiese saltado esa parte al terminar el generador de imágenes. Acabo de hacer los cambios. He mantenido las dos páginas que existen de solo generar nombres y imágenes por su parte y he creado una nueva con un índice que contiene ambas siguiendo [este enlace](https://grand-strudel-87fb30.netlify.app/) o en el apartado 3 del informe: [Página completa](https://github.com/ULL-ESIT-DMSI-2223/nextjs-marta-molina-fernandez-alu0101603360#id5)

Lamento las molestias. Un saludo.

**Comment by crguezl** [comment]
👍 Buen trabajo @MartaMolina01 !
